version: '3.8'

networks:
  my_network:
    name: my_network

services:
  mongo-express:
    container_name: mongoexpress
    hostname: mongoexpress
    image: mongo-express:1.0.0-alpha.4
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=j
      - ME_CONFIG_MONGODB_SERVER=db-mongo
    ports:
      - '8081:8081'
    volumes:
      - ./config:/etc/mongo-express
      - ./certs:/ssl
    networks:
      - my_network
